export const PRODUCTS_FETCHED = 'PRODUCTS_IS_FETCHED';
export const PRODUCTS_ERROR = 'PRODUCTS_IS_ERROR';
export const COUPONS_FETCHED = 'COUPONS_IS_FETCHED';
export const COUPONS_ERROR = 'COUPONS_IS_ERROR';
export const WISHLIST_ADD = 'WISHLIST_ADD';
export const WISHLIST_REMOVE = 'WISHLIST_REMOVE';
export const WISHLIST_ITEM_CHECK = 'WISHLIST_ITEM_CHECK';
export const WISHLIST_ITEM_COUNT = 'WISHLIST_ITEM_COUNT';
export const SELECT_COUPON = 'SELECT_COUPON';
export const TOTAL_PRICE = 'TOTAL_PRICE';
export const PRODUCTS_MAX_SHOW_NO = 5;
export const WISHLIST_MAX_ITEMS_NO = 3;

export enum COUPON_TYPE {
    RATE = 'rate',
    AMOUNT = 'amount'
}